"""Portfolio PDF report generation, ported from the Portfolio Analytics page
in app.py — same structure, rebranded to Longon Capital's dark/emerald palette.
"""
import io
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

BRAND_DARK = colors.HexColor("#0A0E0C")
BRAND_GREEN = colors.HexColor("#0F7B4F")
BRAND_ROW = colors.HexColor("#EAF7F0")


def build_portfolio_pdf(client_name: str, holdings: list, summary: dict,
                          asi_ytd: float, monte_carlo: dict) -> io.BytesIO:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4,
                             rightMargin=50, leftMargin=50, topMargin=50, bottomMargin=50)

    styles = getSampleStyleSheet()
    story = []

    title_style = ParagraphStyle("Title", parent=styles["Heading1"],
                                   fontSize=24, textColor=BRAND_DARK, spaceAfter=10)
    subtitle_style = ParagraphStyle("Subtitle", parent=styles["Normal"],
                                      fontSize=11, textColor=colors.gray, spaceAfter=20)
    body_style = ParagraphStyle("Body", parent=styles["Normal"], fontSize=10, spaceAfter=8)

    total_return = summary["total_return"]

    story.append(Paragraph("Longon Capital", title_style))
    story.append(Paragraph("Nigerian Exchange Portfolio Analytics Report", subtitle_style))
    story.append(Paragraph(f"Client: {client_name}", body_style))
    story.append(Paragraph(f"Report Date: {datetime.now().strftime('%B %d, %Y')}", body_style))
    story.append(Spacer(1, 20))

    header_style = [
        ("BACKGROUND", (0, 0), (-1, 0), BRAND_GREEN),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, BRAND_ROW]),
        ("ALIGN", (1, 0), (1, -1), "RIGHT"),
    ]

    story.append(Paragraph("Portfolio Summary", styles["Heading2"]))
    summary_data = [
        ["Metric", "Value"],
        ["Total Cost", f"NGN {summary['total_cost']:,.2f}"],
        ["Current Value", f"NGN {summary['total_value']:,.2f}"],
        ["Total P&L", f"NGN {summary['total_pnl']:,.2f}"],
        ["Total Return", f"{total_return:.2f}%"],
        ["ASI Benchmark", f"{asi_ytd:.2f}%"],
        ["Alpha", f"{total_return - asi_ytd:.2f}%"],
    ]
    summary_table = Table(summary_data, colWidths=[3 * inch, 3 * inch])
    summary_table.setStyle(TableStyle(header_style))
    story.append(summary_table)
    story.append(Spacer(1, 20))

    story.append(Paragraph("Holdings Breakdown", styles["Heading2"]))
    holdings_data = [["Ticker", "Qty", "Buy Price", "Current", "P&L", "Return %"]]
    for p in holdings:
        holdings_data.append([
            p["ticker"], f"{p['quantity']:,}",
            f"NGN {p['buy_price']:,.2f}",
            f"NGN {p['current_price']:,.2f}",
            f"NGN {p['pnl']:,.2f}",
            f"{p['return_pct']:.2f}%",
        ])
    holdings_table = Table(holdings_data,
                             colWidths=[0.9 * inch, 0.7 * inch, 1.3 * inch, 1.3 * inch, 1.3 * inch, 0.8 * inch])
    holdings_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), BRAND_GREEN),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, BRAND_ROW]),
    ]))
    story.append(holdings_table)
    story.append(Spacer(1, 20))

    story.append(Paragraph("Monte Carlo Simulation — 1,000 Scenarios", styles["Heading2"]))
    mc_data = [
        ["Metric", "Value"],
        ["Expected Value (1 year)", f"NGN {monte_carlo['expected_value']:,.2f}"],
        ["Best Case (95th percentile)", f"NGN {monte_carlo['best_case_95th']:,.2f}"],
        ["Worst Case (5th percentile)", f"NGN {monte_carlo['worst_case_5th']:,.2f}"],
        ["Probability of Profit", f"{monte_carlo['probability_of_profit']:.1%}"],
    ]
    mc_table = Table(mc_data, colWidths=[3 * inch, 3 * inch])
    mc_table.setStyle(TableStyle(header_style))
    story.append(mc_table)
    story.append(Spacer(1, 20))

    story.append(Paragraph("Disclaimer", styles["Heading2"]))
    story.append(Paragraph(
        "This report is generated by Longon Capital for analytical purposes only "
        "and does not constitute investment advice. Past performance does not guarantee "
        "future results. All data is sourced from public market data and may be delayed. "
        f"(c) {datetime.now().year} Longon Capital",
        body_style,
    ))

    doc.build(story)
    buffer.seek(0)
    return buffer
